# [9660] Exercise # 5 - Logistic Regression - Solution
Data file: https://raw.githubusercontent.com/vjavaly/Baruch-CIS-9660/main/data/breast_cancer_diagnosis.csv

## Exercise # 5 Requirements
* Load data into dataframe
* Examine data
  * Check for missing values
* Prepare data for model training and testing
  * Drop non-numeric columns
  * Replace missing values (use any technique)
  * Separate independent and dependent variables
  * Split train and test sets
* Train logistic regression model
  * If you get errors, change appropriate hyperparameters to eliminate errors
* Caluculate and display model performance metrics
  * accuracy
  * classification report
  * confusion matrix

In [1]:
from datetime import datetime
print(f'Run time: {datetime.now().strftime("%D %T")}')

Run time: 09/24/24 12:10:11

### Import libraries

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

### Load data

In [3]:
# Read data from file (breast_cancer_diagnosis.csv) into dataframe
df = pd.read_csv("https://raw.githubusercontent.com/vjavaly/Baruch-CIS-9660/main/data/breast_cancer_diagnosis.csv")

### Examine data

In [4]:
# Review dataframe shape
df.shape

(569, 13)

In [5]:
# Display first few rows of dataframe
df.head()

,id,name,radius,texture,perimeter,area,smoothness,compactness,concavity,symmetry,fractal_dimension,age,diagnosis
0,ID842302,Glynnis Munson,NaN,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.2419,0.07871,35,1
1,ID842517,Lana Behrer,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.1812,0.05667,27,1
2,ID84300903,Devondra Vanvalkenburgh,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.2069,0.05999,31,1
3,ID84348301,Glory Maravalle,NaN,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.2597,0.09744,49,1
4,ID84358402,Mellie Mccurdy,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.1809,0.05883,20,1

Note: NaN in radius column

### Prepare data

#### Drop non-numeric variables
Remember to use "inplace=True"

In [6]:
df.drop(["id", "name"], axis = 1, inplace = True)

In [7]:
# Display first few rows of updated dataframe
df.head()

,radius,texture,perimeter,area,smoothness,compactness,concavity,symmetry,fractal_dimension,age,diagnosis
0,NaN,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.2419,0.07871,35,1
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.1812,0.05667,27,1
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.2069,0.05999,31,1
3,NaN,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.2597,0.09744,49,1
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.1809,0.05883,20,1

#### Check for missing values

In [8]:
df.isnull().sum()

radius               71
texture               0
perimeter             0
area                  0
smoothness            0
compactness           0
concavity             0
symmetry              0
fractal_dimension     0
age                   0
diagnosis             0
dtype: int64

#### Replace missing values

In [9]:
df['radius'].fillna(df['radius'].mean(), inplace=True)

In [10]:
# Display first few rows of updated dataframe
df.head()

,radius,texture,perimeter,area,smoothness,compactness,concavity,symmetry,fractal_dimension,age,diagnosis
0,14.326635,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.2419,0.07871,35,1
1,20.570000,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.1812,0.05667,27,1
2,19.690000,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.2069,0.05999,31,1
3,14.326635,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.2597,0.09744,49,1
4,20.290000,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.1809,0.05883,20,1

#### Check for missing values again

In [11]:
df.isnull().sum()

radius               0
texture              0
perimeter            0
area                 0
smoothness           0
compactness          0
concavity            0
symmetry             0
fractal_dimension    0
age                  0
diagnosis            0
dtype: int64

### Separate independent and dependent variables
* Independent variables: All remaining variables except Diagnosis
* Dependent variable: Diagnosis

In [12]:
X = df.drop("diagnosis", axis = 1)
y = df["diagnosis"]

In [13]:
# Display first few rows of independent variables
X.head()

,radius,texture,perimeter,area,smoothness,compactness,concavity,symmetry,fractal_dimension,age
0,14.326635,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.2419,0.07871,35
1,20.570000,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.1812,0.05667,27
2,19.690000,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.2069,0.05999,31
3,14.326635,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.2597,0.09744,49
4,20.290000,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.1809,0.05883,20

In [14]:
# Display first few rows of dependent variable
y.head()

0    1
1    1
2    1
3    1
4    1
Name: diagnosis, dtype: int64

### Split data into training and test sets

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y,
                                                    test_size=0.3, random_state=42)

### Train Logistic Regression model

In [16]:
model = LogisticRegression()
model.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

### If above results in error, review error message, look up documentation for LogisticRegression, and change model hyperparameter appropriately

In [17]:
# Train model again
model = LogisticRegression(max_iter = 200)
model.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=200)

In [18]:
# Train model again
model = LogisticRegression(max_iter = 300)
model.fit(X_train, y_train)

LogisticRegression(max_iter=300)

### Test model

In [19]:
# Generate predictions against the test set
predictions = model.predict(X_test)

### Model evaluation

In [20]:
# Print model accuracy
accuracy = model.score(X_test, y_test)
print("accuracy = ", round((accuracy * 100), 5), "%")

accuracy =  89.47368 %

In [21]:
# Print classification report
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.90      0.93      0.92       107
           1       0.88      0.83      0.85        64

    accuracy                           0.89       171
   macro avg       0.89      0.88      0.89       171
weighted avg       0.89      0.89      0.89       171

In [22]:
# Print confusion matrix
confusion_matrix(y_test, predictions)

array([[100,   7],
       [ 11,  53]])