# [9660] Exercise # 7 - Support Vector Machine - Solution
Data file:
* https://raw.githubusercontent.com/vjavaly/Baruch-CIS-9660/main/data/healthcare_stroke_2.csv

## Exercise # 7 Requirements
* Load data into dataframe
  * Do NOT use meaningless columns (e.g. 'id') as independent variables
* Examine data
* Use SimpleImputer to replace missing values
* Encode categorical variables
* Standardize independent variables
* Prepare data for model training and testing
  * Separate independent and dependent variables
  * Split train and test sets
* Train support vector classifier model with default hyperparameters
  * Predict using the test set
  * Calculate and display model accuracy
* Train support vector classifier model with at least 2 different hyperparameters
  * Predict using the test set
  * Calculate and display model accuracy

In [ ]:
from datetime import datetime
print(f'Run time: {datetime.now().strftime("%D %T")}')

Run time: 11/03/24 14:33:49

### Import libraries

In [ ]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

### Set global variable

In [ ]:
global RANDOM_STATE
RANDOM_STATE=42

### Load data

In [ ]:
# Use column 'id' as the index column
df = pd.read_csv('https://raw.githubusercontent.com/vjavaly/Baruch-CIS-9660/main/data/healthcare_stroke_2.csv',
                 index_col='id')

### Examine data

In [ ]:
pd.set_option('display.max_columns', None)

In [ ]:
df.shape

(5110, 9)

In [ ]:
df.head()

,gender,age,hypertension,heart_disease,ever_married,avg_glucose_level,bmi,smoking_status,stroke
id,,,,,,,,,
9046,Male,67.0,0,1,Yes,228.69,36.6,formerly smoked,1
51676,Female,61.0,0,0,Yes,202.21,NaN,never smoked,1
31112,Male,80.0,0,1,Yes,105.92,32.5,never smoked,1
60182,Female,49.0,0,0,Yes,171.23,34.4,smokes,1
1665,Female,79.0,1,0,Yes,174.12,24.0,never smoked,1

In [ ]:
# Review distribution of target (stroke) values
df['stroke'].value_counts()

stroke
0    4861
1     249
Name: count, dtype: int64

In [ ]:
df.isnull().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
avg_glucose_level      0
bmi                  201
smoking_status       134
stroke                 0
dtype: int64

### Prepare data

### Use the SimpleImputer to replace missing values

In [ ]:
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
df['bmi'] = imp_mean.fit_transform(df[['bmi']])
imp_most_frequent = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
df['smoking_status'] = imp_most_frequent.fit_transform(df[['smoking_status']]).ravel()

### Encode categorical variables 'gender', 'ever_married' and 'smoking_status'

In [ ]:
df = pd.get_dummies(df, columns=['gender', 'ever_married', 'smoking_status'], dtype=int)

In [ ]:
# Display first few rows of updated dataframe
df.head()

,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke,gender_Female,gender_Male,gender_Other,ever_married_No,ever_married_Yes,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
id,,,,,,,,,,,,,,
9046,67.0,0,1,228.69,36.600000,1,0,1,0,0,1,1,0,0
51676,61.0,0,0,202.21,28.893237,1,1,0,0,0,1,0,1,0
31112,80.0,0,1,105.92,32.500000,1,0,1,0,0,1,0,1,0
60182,49.0,0,0,171.23,34.400000,1,1,0,0,0,1,0,0,1
1665,79.0,1,0,174.12,24.000000,1,1,0,0,0,1,0,1,0

### Separate independent and dependent variables
Dependent variable: 'stroke'

In [ ]:
X = df.drop('stroke', axis=1)     # Independent variables
y = df['stroke']                  # Dependent variable

### Standardize independent variables

In [ ]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[ 1.05143428, -0.32860186,  4.18503199, ...,  1.85566114,
        -1.12475372, -0.52556995],
       [ 0.78607007, -0.32860186, -0.2389468 , ..., -0.53889149,
         0.88908353, -0.52556995],
       [ 1.62639008, -0.32860186,  4.18503199, ..., -0.53889149,
         0.88908353, -0.52556995],
       ...,
       [-0.36384151, -0.32860186, -0.2389468 , ..., -0.53889149,
         0.88908353, -0.52556995],
       [ 0.34379639, -0.32860186, -0.2389468 , ...,  1.85566114,
        -1.12475372, -0.52556995],
       [ 0.03420481, -0.32860186, -0.2389468 , ..., -0.53889149,
        -1.12475372,  1.90269629]])

### Split data into training and test sets

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, stratify=y,
                                                    test_size=0.3,
                                                    random_state=RANDOM_STATE)

### Train SVC model (with default hyperparameters)

In [ ]:
model = SVC(random_state=RANDOM_STATE)
model.fit(X_train, y_train)

SVC(random_state=42)

### Evaluate SVC model

In [ ]:
model_preds = model.predict(X_test)
model_accuracy = accuracy_score(y_test, model_preds)
print(f"Model score: {round((model_accuracy * 100), 5)}%")

Model score: 95.10763%

### Train SVC model (with at least 2 different hyperparameters)

In [ ]:
model = SVC(C=0.5, kernel='linear', class_weight={0: 0.95, 1: 0.05},
            gamma='auto', random_state=RANDOM_STATE)
model.fit(X_train, y_train)

SVC(C=0.5, class_weight={0: 0.95, 1: 0.05}, gamma='auto', kernel='linear',
    random_state=42)

### Evaluate updated SVC model

In [ ]:
model_preds = model.predict(X_test)
model_accuracy = accuracy_score(y_test, model_preds)
print(f"Model score: {round((model_accuracy * 100), 5)}%")

Model score: 95.10763%